name: usb-backup
version: 0.0.1
slug: usb-backup
description: Plug in a usb drive and backup home assistant
url: https://github.com/Poeschl/Hassio-Addons/tree/main/rsync-local
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
homeassistant: 0.115.0
boot: manual
init: false
hassio_api: true
host_network: true
ports: {}
ports_description: {}
map:
  - share:rw
  - config:rw
  - backup:rw
  - addons:rw
  - ssl:rw
  - media:rw
devices:
  - /dev/sdc1
  - /dev/sdc2
  - /dev/sdc3
  - /dev/sdb1
  - /dev/sdb2
  - /dev/sdb3
  - /dev/sda1
  - /dev/sda2
  - /dev/sda3
privileged:
  - SYS_ADMIN
apparmor: false
schema:
  folders:
    - source: str
      options: str?
  external_folder: match(^[^/].+)
  external_device: match(^(/dev/sd[a|b|c][1|2|3])?)
  snapshots: bool
  snapshot_keep_days: int
options:
  folders:
    - source: /config
    - source: /share
    - source: /media
    - source: /addons
    - source: /ssl
  external_folder: backup
  external_device: ""
  snapshots: true
  snapshot_keep_days: 60
